# Generated by Django 3.2.4 on 2021-06-12 05:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210504_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_instance',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 19, 3, 402521)),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='comment_instance',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 19, 3, 404514)),
        ),
        migrations.AlterField(
            model_name='newsvote',
            name='vote_instance',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 19, 3, 414488)),
        ),
    ]
